// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by generate_data.py from data/*.json
#pragma once

#include <string>
#include <unordered_map>
#include <vector>
#include <cstdint>

enum class GoodType : uint16_t {
    WHEAT,
    MEAT,
    FISH,
    WOOD,
    STONE,
    IRON_ORE,
    GOLD_ORE,
    COTTON,
    HERBS,
    ETHER_DUST,
    FLOUR,
    BREAD,
    SMOKED_MEAT,
    IRON_INGOT,
    GOLD_INGOT,
    BOARDS,
    CLOTH,
    CLOTHES,
    WEAPONS,
    ARMOR,
    POTIONS,
    JEWELRY,
    DOCUMENT_ORDER,
    SICKLE,
    PICKAXE,
    AXE,
    HAMMER,
    WAGON,
    HONEY,
    WAX,
    FUR,
    MONSTER_PARTS,
    PERFUME,
    LINGERIE,
    APHRODISIAC,
    COUNT
};

// Names for each era: rebirth, architects, sundering, silence
struct GoodNames {
    std::string rebirth;
    std::string architects;
    std::string sundering;
    std::string silence;
};

const GoodNames GOOD_NAMES[] = {
    { "Пшеница", "Био-масса", "Пепельные грибы", "Гидропоника" }, // wheat
    { "Сырое мясо", "Синтезированный белок", "Мясо мутантов", "Брикеты плоти" }, // meat
    { "Рыба", "Питательная паста", "Глубинные черви", "Консервы Предтеч" }, // fish
    { "Древесина", "Силикатный полимер", "Окаменелая кость", "Утильсырье" }, // wood
    { "Камень", "Базальт", "Мертвый камень", "Бетон" }, // stone
    { "Железная руда", "Сырой Эфир", "Радиоактивный шлак", "Детали машин" }, // iron_ore
    { "Золотая руда", "Кристаллы Памяти", "Осколки Разлома", "Рабочие микрочипы" }, // gold_ore
    { "Хлопок", "Нано-волокно", "Паутина Бездны", "Старые провода" }, // cotton
    { "Травы", "Генные стимуляторы", "Ядовитые споры", "Медикаменты" }, // herbs
    { "Эфирная пыль", "Очищенный Эфир", "Прах", "Заряженные Батареи" }, // ether_dust
    { "Мука", "Протеиновый порошок", "Костяная мука", "Сухпаек" }, // flour
    { "Хлеб", "Энерго-батончик", "Спекшийся паек", "Синтетические крекеры" }, // bread
    { "Копченое мясо", "Пищевой концентрат", "Вяленая плоть", "Сушеное мясо" }, // smoked_meat
    { "Железный слиток", "Керамитовый сплав", "Очищенный шлак", "Спрессованный лом" }, // iron_ingot
    { "Золотой слиток", "Блок памяти", "Активный артефакт", "Редкая электроника" }, // gold_ingot
    { "Доски", "Полимерные панели", "Укрепленные кости", "Сборный пластик" }, // boards
    { "Ткань", "Синтетика", "Толстая паутина", "Крепкая изоляция" }, // cloth
    { "Одежда", "Умные костюмы", "Защитные плащи", "Спецодежда" }, // clothes
    { "Оружие", "Энерго-оружие", "Ржавое оружие", "Огнестрел" }, // weapons
    { "Броня", "Силовые щиты", "Хитиновые панцири", "Свинец и Кевлар" }, // armor
    { "Зелья", "Нано-инъекции", "Экстракты мутагенов", "Стимуляторы" }, // potions
    { "Ювелирные изделия", "Голо-украшения", "Жуткие трофеи", "Реликвии прошлого" }, // jewelry
    { "Письмо-заказ", "Инфо-контракт", "Долговая кость", "Перфокарта заказа" }, // document_order
    { "Серп", "Био-резак", "Костяной серп", "Ржавый серп" }, // sickle
    { "Кирка", "Плазменный бур", "Шлаковая кирка", "Шахтерская кирка" }, // pickaxe
    { "Топор", "Лазерный резак", "Топор из челюсти", "Пожарный топор" }, // axe
    { "Молот", "Грави-пресс", "Каменный молот", "Кувалда" }, // hammer
    { "Торговая повозка", "Грави-платформа", "Костяной возок", "Ржавая фура" }, // wagon
    { "Мёд", "Синтез-нектар", "Сладкая гниль", "Дикий мёд" }, // honey
    { "Воск", "Био-герметик", "Трупный жир", "Парафин" }, // wax
    { "Меха", "Термо-ткань", "Шкуры мутантов", "Грязный мех" }, // fur
    { "Части чудовищ", "Био-трофеи", "Эфирные останки", "Мутагенные железы" }, // monster_parts
    { "Духи", "Феромоны", "Мускус", "Ароматизатор" }, // perfume
    { "Кружевное белье", "Синтетический шелк", "Кожаный корсет", "Чистое белье" }, // lingerie
    { "Афродизиак", "Стимулятор либидо", "Кровь суккуба", "Порошок страсти" }, // aphrodisiac
};

const int BASE_PRICES[] = {
    1, // wheat
    2, // meat
    2, // fish
    2, // wood
    3, // stone
    3, // iron_ore
    20, // gold_ore
    2, // cotton
    4, // herbs
    15, // ether_dust
    3, // flour
    5, // bread
    6, // smoked_meat
    10, // iron_ingot
    100, // gold_ingot
    5, // boards
    8, // cloth
    20, // clothes
    40, // weapons
    50, // armor
    35, // potions
    150, // jewelry
    0, // document_order
    15, // sickle
    20, // pickaxe
    15, // axe
    20, // hammer
    500, // wagon
    8, // honey
    4, // wax
    12, // fur
    500, // monster_parts
    50, // perfume
    40, // lingerie
    100, // aphrodisiac
};

enum class GoodCategory : uint8_t {
    ARMOR,
    BUILDING,
    CLOTH,
    CONSUMABLE,
    DOCUMENT,
    LUXURY,
    MAGIC_RAW,
    METAL_INGOT,
    PROCESSED_FOOD,
    RAW_FOOD,
    RAW_MATERIAL,
    TOOL,
    VEHICLE,
    WEAPON,
    COUNT
};

const GoodCategory GOOD_CATEGORIES[] = {
    GoodCategory::RAW_FOOD, // wheat
    GoodCategory::RAW_FOOD, // meat
    GoodCategory::RAW_FOOD, // fish
    GoodCategory::RAW_MATERIAL, // wood
    GoodCategory::RAW_MATERIAL, // stone
    GoodCategory::RAW_MATERIAL, // iron_ore
    GoodCategory::RAW_MATERIAL, // gold_ore
    GoodCategory::RAW_MATERIAL, // cotton
    GoodCategory::MAGIC_RAW, // herbs
    GoodCategory::MAGIC_RAW, // ether_dust
    GoodCategory::PROCESSED_FOOD, // flour
    GoodCategory::CONSUMABLE, // bread
    GoodCategory::CONSUMABLE, // smoked_meat
    GoodCategory::METAL_INGOT, // iron_ingot
    GoodCategory::METAL_INGOT, // gold_ingot
    GoodCategory::BUILDING, // boards
    GoodCategory::CLOTH, // cloth
    GoodCategory::LUXURY, // clothes
    GoodCategory::WEAPON, // weapons
    GoodCategory::ARMOR, // armor
    GoodCategory::CONSUMABLE, // potions
    GoodCategory::LUXURY, // jewelry
    GoodCategory::DOCUMENT, // document_order
    GoodCategory::TOOL, // sickle
    GoodCategory::TOOL, // pickaxe
    GoodCategory::TOOL, // axe
    GoodCategory::TOOL, // hammer
    GoodCategory::VEHICLE, // wagon
    GoodCategory::RAW_FOOD, // honey
    GoodCategory::RAW_MATERIAL, // wax
    GoodCategory::RAW_MATERIAL, // fur
    GoodCategory::MAGIC_RAW, // monster_parts
    GoodCategory::LUXURY, // perfume
    GoodCategory::LUXURY, // lingerie
    GoodCategory::CONSUMABLE, // aphrodisiac
};

struct Recipe {
    std::string facility;
    std::unordered_map<GoodType, int> inputs;
    std::unordered_map<GoodType, int> outputs;
};

const std::vector<Recipe> RECIPES = {
    {
        "mills",
        {
            {GoodType::WHEAT, 2}
        },
        {
            {GoodType::FLOUR, 1}
        }
    },
    {
        "bakeries",
        {
            {GoodType::FLOUR, 1}
        },
        {
            {GoodType::BREAD, 2}
        }
    },
    {
        "smokehouses",
        {
            {GoodType::MEAT, 1}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::SMOKED_MEAT, 1}
        }
    },
    {
        "lumbermills",
        {
            {GoodType::WOOD, 1}
        },
        {
            {GoodType::BOARDS, 2}
        }
    },
    {
        "smelters",
        {
            {GoodType::IRON_ORE, 2}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::IRON_INGOT, 1}
        }
    },
    {
        "smelters",
        {
            {GoodType::GOLD_ORE, 2}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::GOLD_INGOT, 1}
        }
    },
    {
        "weavers",
        {
            {GoodType::COTTON, 2}
        },
        {
            {GoodType::CLOTH, 1}
        }
    },
    {
        "tailors",
        {
            {GoodType::CLOTH, 2}
        },
        {
            {GoodType::CLOTHES, 1}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 2}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::WEAPONS, 1}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 3}, {GoodType::CLOTH, 1}
        },
        {
            {GoodType::ARMOR, 1}
        }
    },
    {
        "alchemists",
        {
            {GoodType::HERBS, 2}, {GoodType::ETHER_DUST, 1}
        },
        {
            {GoodType::POTIONS, 1}
        }
    },
    {
        "jewelers",
        {
            {GoodType::GOLD_INGOT, 1}
        },
        {
            {GoodType::JEWELRY, 1}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 1}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::SICKLE, 2}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 2}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::PICKAXE, 2}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 1}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::AXE, 2}
        }
    },
    {
        "forges",
        {
            {GoodType::IRON_INGOT, 2}, {GoodType::WOOD, 1}
        },
        {
            {GoodType::HAMMER, 2}
        }
    },
    {
        "lumbermills",
        {
            {GoodType::WOOD, 10}, {GoodType::IRON_INGOT, 2}
        },
        {
            {GoodType::WAGON, 1}
        }
    },
    {
        "alchemists",
        {
            {GoodType::HERBS, 3}
        },
        {
            {GoodType::PERFUME, 1}
        }
    },
    {
        "tailors",
        {
            {GoodType::CLOTH, 1}
        },
        {
            {GoodType::LINGERIE, 2}
        }
    },
    {
        "alchemists",
        {
            {GoodType::MONSTER_PARTS, 1}, {GoodType::HERBS, 1}
        },
        {
            {GoodType::APHRODISIAC, 1}
        }
    },
};

inline const char* getFacilityName(const std::string& id) {
    static std::unordered_map<std::string, const char*> names = {
        {"farms", "farms"},
        {"lumbermills", "lumbermills"},
        {"mines", "mines"},
        {"forges", "forges"},
        {"smelters", "smelters"},
        {"weavers", "weavers"},
        {"bakeries", "bakeries"},
        {"smokehouses", "smokehouses"},
        {"alchemists", "alchemists"},
        {"banks", "banks"},
        {"mills", "mills"},
        {"tailors", "tailors"},
        {"jewelers", "jewelers"},
        {"warehouses", "warehouses"},
        {"apiaries", "apiaries"},
        {"hunting_lodges", "hunting_lodges"},
        {"observatories", "observatories"},
        {"shipyards", "shipyards"},
        {"fisheries", "fisheries"},
        {"brothels", "brothels"},
        {"bathhouses", "bathhouses"},
    };
    auto it = names.find(id);
    return it != names.end() ? it->second : id.c_str();
}

inline GoodType stringToGoodType(const std::string& name) {
    static std::unordered_map<std::string, GoodType> mapping = {
        {"wheat", GoodType::WHEAT},
        {"meat", GoodType::MEAT},
        {"fish", GoodType::FISH},
        {"wood", GoodType::WOOD},
        {"stone", GoodType::STONE},
        {"iron_ore", GoodType::IRON_ORE},
        {"gold_ore", GoodType::GOLD_ORE},
        {"cotton", GoodType::COTTON},
        {"herbs", GoodType::HERBS},
        {"ether_dust", GoodType::ETHER_DUST},
        {"flour", GoodType::FLOUR},
        {"bread", GoodType::BREAD},
        {"smoked_meat", GoodType::SMOKED_MEAT},
        {"iron_ingot", GoodType::IRON_INGOT},
        {"gold_ingot", GoodType::GOLD_INGOT},
        {"boards", GoodType::BOARDS},
        {"cloth", GoodType::CLOTH},
        {"clothes", GoodType::CLOTHES},
        {"weapons", GoodType::WEAPONS},
        {"armor", GoodType::ARMOR},
        {"potions", GoodType::POTIONS},
        {"jewelry", GoodType::JEWELRY},
        {"document_order", GoodType::DOCUMENT_ORDER},
        {"sickle", GoodType::SICKLE},
        {"pickaxe", GoodType::PICKAXE},
        {"axe", GoodType::AXE},
        {"hammer", GoodType::HAMMER},
        {"wagon", GoodType::WAGON},
        {"honey", GoodType::HONEY},
        {"wax", GoodType::WAX},
        {"fur", GoodType::FUR},
        {"monster_parts", GoodType::MONSTER_PARTS},
        {"perfume", GoodType::PERFUME},
        {"lingerie", GoodType::LINGERIE},
        {"aphrodisiac", GoodType::APHRODISIAC},
    };
    auto it = mapping.find(name);
    return it != mapping.end() ? it->second : GoodType::COUNT;
}

struct MaterialTemplate {
    std::string id;
    int health = 100;
    bool flammable = false;
    double insulation = 0.0;
};

inline const std::unordered_map<std::string, MaterialTemplate>& getMaterialCatalog() {
    static std::unordered_map<std::string, MaterialTemplate> catalog = {
        {"wood", {"wood", 200, true, 0.5}},
        {"stone", {"stone", 500, false, 0.8}},
        {"brick", {"brick", 400, false, 0.7}},
        {"dirt", {"dirt", 100, false, 0.2}},
        {"cobble", {"cobble", 300, false, 0.4}},
    };
    return catalog;
}

struct FurnitureTemplate {
    std::string id;
    std::string category;
    std::string name;
    int health = 100;
    int weight = 10;
    bool flammable = true;
    bool is_container = false;
    int max_weight = 0;
    int max_slots = 0;
};

inline const std::unordered_map<std::string, FurnitureTemplate>& getFurnitureCatalog() {
    static std::unordered_map<std::string, FurnitureTemplate> catalog = {
        {"chest_raw_materials", {"chest_raw_materials", "storage", "Склад сырья", 200, 50, true, true, 5000, 100}},
        {"chest_finished_goods", {"chest_finished_goods", "storage", "Склад продукции", 200, 50, true, true, 5000, 100}},
        {"personal_storage_poor", {"personal_storage_poor", "storage", "Старый сундук", 50, 15, true, true, 100, 20}},
        {"personal_storage_rich", {"personal_storage_rich", "storage", "Резной шкаф", 100, 40, true, true, 200, 40}},
        {"wooden_bed", {"wooden_bed", "bed", "Деревянная кровать", 50, 30, true, false, 0, 0}},
        {"stone_well", {"stone_well", "outdoor", "Каменный колодец", 1000, 2000, false, false, 0, 0}},
        {"street_lantern", {"street_lantern", "outdoor", "Уличный фонарь", 30, 10, false, false, 0, 0}},
    };
    return catalog;
}

inline const std::string& goodTypeToString(GoodType type) {
    static std::vector<std::string> names = {
        "wheat",
        "meat",
        "fish",
        "wood",
        "stone",
        "iron_ore",
        "gold_ore",
        "cotton",
        "herbs",
        "ether_dust",
        "flour",
        "bread",
        "smoked_meat",
        "iron_ingot",
        "gold_ingot",
        "boards",
        "cloth",
        "clothes",
        "weapons",
        "armor",
        "potions",
        "jewelry",
        "document_order",
        "sickle",
        "pickaxe",
        "axe",
        "hammer",
        "wagon",
        "honey",
        "wax",
        "fur",
        "monster_parts",
        "perfume",
        "lingerie",
        "aphrodisiac",
    };
    if (static_cast<size_t>(type) < names.size()) return names[static_cast<size_t>(type)];
    static std::string unknown = "unknown";
    return unknown;
}
